### ISSUE TITLE
Write first blog post

### ISSUE THREAD

**Issue by kostajh** [durhamatletico/durhamatletico.github.io#2]
To replace the Kafka story

**Comment by davidfellerath** [comment]
Here's the opening blog post. I can email as a word doc, too, if that's better.

There's a lot to say about this project and why we're doing it, but I'm determined to keep this to 300 words. There's plenty of time to elaborate as we push forward with the adventure we're calling Durham  Atlético.

Durham  Atlético is a response to a serious imbalance of resources and needs in in our community. 

Simply put, there are far more people looking for places to play soccer than there are places to play. This affects everyone, but it affects urban communities most acutely. Durham has several nice public fields, but they are located in the suburbs, and they are consistently oversubscribed. 

It's no secret that there's a field shortage. It's also no secret that it is difficult to find funds for investing in our public athletic infrastructure. Durham  Atlético exists because we hope to be part of the solution.

Why are we called Durham Atlético? Let me explain our name with a story. 

Today I went to the bank to open our business checking account. The bank's representative was a young woman of Hispanic descent. She's lived in Durham most of her life. In the course of processing my application, she asked about the nature of the business (soccer). 

She then noticed the name. “Oh! Durham Atlehhhtico!” 

“Do you play soccer?” I asked. “Do you want to play with us?”

“No, but my boyfriend plays!”

She told me her boyfriend's teams constantly have trouble finding fields, playing in random, unpredictable places from week to week. Often, there are scheduling mix-ups, and teams have to wait while other teams finish playing.

“Will you tell him about Durham  Atlético?”

“Definitely.”

“OK. Let me write down the website for you--”

“No need. I'll remember that name!”

So Durham Atlético it is. We're excited about this and we hope you'll join us.

**Comment by kostajh** [comment]
@davidfellerath thanks, title of post?

**Comment by davidfellerath** [comment]
Why Durham Atlético?

**Comment by kostajh** [comment]
@davidfellerath done! http://durhamatletico.com/2015/01/22/why-durham-atletico.html

**Comment by davidfellerath** [comment]
Great!
