### ISSUE TITLE
Fill out Futsal league info

### ISSUE THREAD

**Issue by kostajh** [durhamatletico/durhamatletico.github.io#3]
http://durhamatletico.com/futsal/

**Comment by davidfellerath** [comment]
WINTER FUTSAL LEAGUE 2015

It's our pleasure to announce that Durham Atlético's Winter Futsal League is officially open, and we invite you to join us on Tuesday nights beginning Feb. 3! 

We have room for six teams, and four have already been filled. This will be a great opportunity to try out the game that nurtured so many great South American talents, although we can't promise you'll be dribbling like Ronaldinho after playing with us.

This will be a lot of fun, and we hope you'll join us. We are using Durham Atlético as a springboard to push for better soccer facilities in Durham. Money we earn from this league, and future ones like it, will go toward improving Durham's public soccer facilities. The shortage of fields in Durham affects urban children most acutely, particularly Latinos and African-Americans.

We are joined by generous and enthusiastic sponsors including Bull McCabe's, Mattie B's and Motorco. They've contributed their support because they love soccer, and of course, their establishments will be great places for us to celebrate our victories (or lament our defeats).

The price is $90 per person. Some of you may be making payment payment arrangement). We do not want anyone to be deterred by the cost. Get in touch with us for other options if the fee is too high, at info@durhamatletico.com 

SCHEDULE

We will begin play Tuesday, Feb. 6, from 6-9pm for nine or 10 weeks. Three games lasting one hour each will be played. Once we have all teams registered, we will post a detailed schedule. 
 
The location will  be Weaver Street Recreation Center in South Durham


ABOUT FUTSAL

Futsal is a form of 5 v. 5 soccer, with goalkeepers.

It is similar to the conventional indoor soccer that Americans are used to, except that the ball is smaller and less bouncy. As result, the emphasis is on control and footwork. 

The game was invented in Uruguay in the 1930s, and it's one of the reasons South America produces so many technically brilliant players. (Google "Ronaldinho + futsal!)

We will play on a small basketball court at Weaver Street Recreation Center, where we will have experienced, certified referees to ensure that the game's unique rules are followed.

Among the key differences between futsal and normal soccer, indoor or outdoor:

Instead of throw-ins, balls are played in with a kick-in.
Substitutions are unlimited, and they can take place during the flow of the game, as with hockey.
No slide tackles or shoulder charges.
Each half will be 25 minutes long, with no stoppages.
Keepers have four seconds to release the ball. 
Keepers may receive only one back pass per possession (and may not pick up a back pass).

These are the key differences, but mostly, it's just soccer!

FAQ

Do you have insurance?  
We do not have medical, only the general liability that is required by Durham Parks and Rec. We will need waivers signed.

I don't have a team. How do I play?
That's easy! Just register as a free agent.

I'd like to play, but the cost is prohibitive.
We don't want to turn anyone away for lack of funds. If this is an issue, please contact us at info@durhamatletico.com.

Is Durham Atletico a nonprofit?
Technically, no. We are a limited liability company. However, this company is not designed to be profitable, but to further social goals. For more, visit (ABOUT US)


SOCIAL
Contact: info@durhamatletico.com
Look for us on Twitter (@durhamatletico) and Facebook.
