### ISSUE TITLE
Create Transparency page content

### ISSUE THREAD

**Issue by kostajh** [durhamatletico/durhamatletico.github.io#5]
@davidfellerath where should this live? Put a link in the Footer?

**Comment by davidfellerath** [comment]
We chose to incorporate Durham Atlético as a limited liability company because it was the simplest, most economical way to get started on our goals here in Durham. However, we are operating Durham Atlético as a community-oriented social enterprise, not as a profit-making venture. We will not collect more money than we need to achieve our stated goals. In time, we may shift to a business structure that can tackle more complex objectives, but until then, our finances will be very simple. If you're interested in looking at our current project budget, look for a link on this page (we'll put it up as soon as we can). Please address additional questions to info@durhamatletico.com

**Comment by davidfellerath** [comment]
Copy is written.

**Comment by kostajh** [comment]
Reopening till we post it :-0

**Comment by kostajh** [comment]
And, that's done now!
