### ISSUE TITLE
Write promotional email content for futsal league

### ISSUE THREAD

**Issue by kostajh** [durhamatletico/durhamatletico.github.io#6]
@davidfellerath can you draft 1-2 paragraphs announcing the league and encouraging people to register?

**Comment by davidfellerath** [comment]
[GREETINGS]

As some of you know, [WE, DAVID FELLERATH AND I, ETC] have been putting together a winter futsal league. It's our pleasure to announce that Durham Atlético's Winter Futsal League is officially open, and we invite you to join us on Tuesday nights beginning Feb. 3! 

We have room for six teams, and about four have already been filled. This will be a great opportunity to try out the game that nurtured so many great South American talents, although we can't promise you'll be dribbling like Ronaldinho after playing with us.

Before you read on, you can register right now! Visit durhamatletico.com.

This will be a lot of fun, and we hope you'll join us. We want to stress that we are using Durham Atlético as a springboard to push for better soccer facilities in Durham. Money we earn from this league, and future ones like it, will go toward improving Durham's public soccer facilities. Our first target is Campus Hills Park, which has a large, unused softball field that would be perfect for 8v8 adult soccer league games. It would be even better if this field could be used for urban youth leagues, and our hope is that we can make this possible. (The shortage of fields in Durham affects urban children most acutely, particularly Latinos and African-Americans.)

We are joined by generous and enthusiastic sponsors including Bull McCabe's, Mattie B's and Motorco. They've contributed their support because they love soccer, and of course, they'd love it if we'd come hang out with them after games. 

The deets: 

Price: $90
Length of season: Nine or ten weeks
Location: Weaver Street Recreation Center in South Durham
Time: Games will last one hour and will be played from 6-9pm
Start date: Tuesday, Feb. 3
Where to register: durhamatletico.com
Where to pay: On the website or in person at the first game (we will take credit cards)
Insurance: We do not have medical, only general liability. We will need waivers signed.
Contact: info@durhamatletico.com
Look for us on Twitter (@durhamatletico) and Facebook.

We do not want anyone to be deterred by the cost. Let us know if we can help you play.

**Comment by davidfellerath** [comment]
How is this? Notice that the parts in ALLCAPS are there for you to modify as you see fit.

**Comment by davidfellerath** [comment]
Just noticed you said 1-2 paragraphs. Too much?

**Comment by kostajh** [comment]
@davidfellerath Looks good. I'll make some edits. Let's adapt this for #2 as well. Let's coordinate on IM about which listservs we can send this out to.

**Comment by kostajh** [comment]
@davidfellerath what's the subject line?
